// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/pagamento/pagamento.proto

package pagamento

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuctionWinnerNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeilaoId      string                 `protobuf:"bytes,1,opt,name=leilao_id,json=leilaoId,proto3" json:"leilao_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Valor         float64                `protobuf:"fixed64,3,opt,name=valor,proto3" json:"valor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionWinnerNotification) Reset() {
	*x = AuctionWinnerNotification{}
	mi := &file_proto_pagamento_pagamento_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionWinnerNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionWinnerNotification) ProtoMessage() {}

func (x *AuctionWinnerNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pagamento_pagamento_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionWinnerNotification.ProtoReflect.Descriptor instead.
func (*AuctionWinnerNotification) Descriptor() ([]byte, []int) {
	return file_proto_pagamento_pagamento_proto_rawDescGZIP(), []int{0}
}

func (x *AuctionWinnerNotification) GetLeilaoId() string {
	if x != nil {
		return x.LeilaoId
	}
	return ""
}

func (x *AuctionWinnerNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuctionWinnerNotification) GetValor() float64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

type PaymentLinkNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PaymentLink   string                 `protobuf:"bytes,2,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AuctionId     string                 `protobuf:"bytes,4,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentLinkNotification) Reset() {
	*x = PaymentLinkNotification{}
	mi := &file_proto_pagamento_pagamento_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentLinkNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentLinkNotification) ProtoMessage() {}

func (x *PaymentLinkNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pagamento_pagamento_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentLinkNotification.ProtoReflect.Descriptor instead.
func (*PaymentLinkNotification) Descriptor() ([]byte, []int) {
	return file_proto_pagamento_pagamento_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentLinkNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentLinkNotification) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

func (x *PaymentLinkNotification) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentLinkNotification) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

type PaymentStatusNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	AuctionId     string                 `protobuf:"bytes,4,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentStatusNotification) Reset() {
	*x = PaymentStatusNotification{}
	mi := &file_proto_pagamento_pagamento_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentStatusNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentStatusNotification) ProtoMessage() {}

func (x *PaymentStatusNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pagamento_pagamento_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentStatusNotification.ProtoReflect.Descriptor instead.
func (*PaymentStatusNotification) Descriptor() ([]byte, []int) {
	return file_proto_pagamento_pagamento_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentStatusNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentStatusNotification) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentStatusNotification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentStatusNotification) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_pagamento_pagamento_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pagamento_pagamento_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_pagamento_pagamento_proto_rawDescGZIP(), []int{3}
}

var File_proto_pagamento_pagamento_proto protoreflect.FileDescriptor

const file_proto_pagamento_pagamento_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/pagamento/pagamento.proto\x12\tpagamento\"g\n" +
	"\x19AuctionWinnerNotification\x12\x1b\n" +
	"\tleilao_id\x18\x01 \x01(\tR\bleilaoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05valor\x18\x03 \x01(\x01R\x05valor\"\x9b\x01\n" +
	"\x17PaymentLinkNotification\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fpayment_link\x18\x02 \x01(\tR\vpaymentLink\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x04 \x01(\tR\tauctionId\"\x92\x01\n" +
	"\x19PaymentStatusNotification\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x04 \x01(\tR\tauctionId\"\a\n" +
	"\x05Empty2\xfb\x01\n" +
	"\x10PagamentoService\x12M\n" +
	"\x13NotifyAuctionWinner\x12$.pagamento.AuctionWinnerNotification\x1a\x10.pagamento.Empty\x12I\n" +
	"\x11NotifyPaymentLink\x12\".pagamento.PaymentLinkNotification\x1a\x10.pagamento.Empty\x12M\n" +
	"\x13NotifyPaymentStatus\x12$.pagamento.PaymentStatusNotification\x1a\x10.pagamento.EmptyB Z\x1eauction-system/proto/pagamentob\x06proto3"

var (
	file_proto_pagamento_pagamento_proto_rawDescOnce sync.Once
	file_proto_pagamento_pagamento_proto_rawDescData []byte
)

func file_proto_pagamento_pagamento_proto_rawDescGZIP() []byte {
	file_proto_pagamento_pagamento_proto_rawDescOnce.Do(func() {
		file_proto_pagamento_pagamento_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pagamento_pagamento_proto_rawDesc), len(file_proto_pagamento_pagamento_proto_rawDesc)))
	})
	return file_proto_pagamento_pagamento_proto_rawDescData
}

var file_proto_pagamento_pagamento_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_pagamento_pagamento_proto_goTypes = []any{
	(*AuctionWinnerNotification)(nil), // 0: pagamento.AuctionWinnerNotification
	(*PaymentLinkNotification)(nil),   // 1: pagamento.PaymentLinkNotification
	(*PaymentStatusNotification)(nil), // 2: pagamento.PaymentStatusNotification
	(*Empty)(nil),                     // 3: pagamento.Empty
}
var file_proto_pagamento_pagamento_proto_depIdxs = []int32{
	0, // 0: pagamento.PagamentoService.NotifyAuctionWinner:input_type -> pagamento.AuctionWinnerNotification
	1, // 1: pagamento.PagamentoService.NotifyPaymentLink:input_type -> pagamento.PaymentLinkNotification
	2, // 2: pagamento.PagamentoService.NotifyPaymentStatus:input_type -> pagamento.PaymentStatusNotification
	3, // 3: pagamento.PagamentoService.NotifyAuctionWinner:output_type -> pagamento.Empty
	3, // 4: pagamento.PagamentoService.NotifyPaymentLink:output_type -> pagamento.Empty
	3, // 5: pagamento.PagamentoService.NotifyPaymentStatus:output_type -> pagamento.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pagamento_pagamento_proto_init() }
func file_proto_pagamento_pagamento_proto_init() {
	if File_proto_pagamento_pagamento_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pagamento_pagamento_proto_rawDesc), len(file_proto_pagamento_pagamento_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pagamento_pagamento_proto_goTypes,
		DependencyIndexes: file_proto_pagamento_pagamento_proto_depIdxs,
		MessageInfos:      file_proto_pagamento_pagamento_proto_msgTypes,
	}.Build()
	File_proto_pagamento_pagamento_proto = out.File
	file_proto_pagamento_pagamento_proto_goTypes = nil
	file_proto_pagamento_pagamento_proto_depIdxs = nil
}
