// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/pagamento/pagamento.proto

package pagamento

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PagamentoService_NotifyAuctionWinner_FullMethodName = "/pagamento.PagamentoService/NotifyAuctionWinner"
	PagamentoService_NotifyPaymentLink_FullMethodName   = "/pagamento.PagamentoService/NotifyPaymentLink"
	PagamentoService_NotifyPaymentStatus_FullMethodName = "/pagamento.PagamentoService/NotifyPaymentStatus"
)

// PagamentoServiceClient is the client API for PagamentoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PagamentoServiceClient interface {
	NotifyAuctionWinner(ctx context.Context, in *AuctionWinnerNotification, opts ...grpc.CallOption) (*Empty, error)
	NotifyPaymentLink(ctx context.Context, in *PaymentLinkNotification, opts ...grpc.CallOption) (*Empty, error)
	NotifyPaymentStatus(ctx context.Context, in *PaymentStatusNotification, opts ...grpc.CallOption) (*Empty, error)
}

type pagamentoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPagamentoServiceClient(cc grpc.ClientConnInterface) PagamentoServiceClient {
	return &pagamentoServiceClient{cc}
}

func (c *pagamentoServiceClient) NotifyAuctionWinner(ctx context.Context, in *AuctionWinnerNotification, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PagamentoService_NotifyAuctionWinner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pagamentoServiceClient) NotifyPaymentLink(ctx context.Context, in *PaymentLinkNotification, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PagamentoService_NotifyPaymentLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pagamentoServiceClient) NotifyPaymentStatus(ctx context.Context, in *PaymentStatusNotification, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PagamentoService_NotifyPaymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PagamentoServiceServer is the server API for PagamentoService service.
// All implementations must embed UnimplementedPagamentoServiceServer
// for forward compatibility.
type PagamentoServiceServer interface {
	NotifyAuctionWinner(context.Context, *AuctionWinnerNotification) (*Empty, error)
	NotifyPaymentLink(context.Context, *PaymentLinkNotification) (*Empty, error)
	NotifyPaymentStatus(context.Context, *PaymentStatusNotification) (*Empty, error)
	mustEmbedUnimplementedPagamentoServiceServer()
}

// UnimplementedPagamentoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPagamentoServiceServer struct{}

func (UnimplementedPagamentoServiceServer) NotifyAuctionWinner(context.Context, *AuctionWinnerNotification) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyAuctionWinner not implemented")
}
func (UnimplementedPagamentoServiceServer) NotifyPaymentLink(context.Context, *PaymentLinkNotification) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyPaymentLink not implemented")
}
func (UnimplementedPagamentoServiceServer) NotifyPaymentStatus(context.Context, *PaymentStatusNotification) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyPaymentStatus not implemented")
}
func (UnimplementedPagamentoServiceServer) mustEmbedUnimplementedPagamentoServiceServer() {}
func (UnimplementedPagamentoServiceServer) testEmbeddedByValue()                          {}

// UnsafePagamentoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PagamentoServiceServer will
// result in compilation errors.
type UnsafePagamentoServiceServer interface {
	mustEmbedUnimplementedPagamentoServiceServer()
}

func RegisterPagamentoServiceServer(s grpc.ServiceRegistrar, srv PagamentoServiceServer) {
	// If the following call panics, it indicates UnimplementedPagamentoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PagamentoService_ServiceDesc, srv)
}

func _PagamentoService_NotifyAuctionWinner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionWinnerNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagamentoServiceServer).NotifyAuctionWinner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PagamentoService_NotifyAuctionWinner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagamentoServiceServer).NotifyAuctionWinner(ctx, req.(*AuctionWinnerNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _PagamentoService_NotifyPaymentLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentLinkNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagamentoServiceServer).NotifyPaymentLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PagamentoService_NotifyPaymentLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagamentoServiceServer).NotifyPaymentLink(ctx, req.(*PaymentLinkNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _PagamentoService_NotifyPaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentStatusNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagamentoServiceServer).NotifyPaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PagamentoService_NotifyPaymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagamentoServiceServer).NotifyPaymentStatus(ctx, req.(*PaymentStatusNotification))
	}
	return interceptor(ctx, in, info, handler)
}

// PagamentoService_ServiceDesc is the grpc.ServiceDesc for PagamentoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PagamentoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pagamento.PagamentoService",
	HandlerType: (*PagamentoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyAuctionWinner",
			Handler:    _PagamentoService_NotifyAuctionWinner_Handler,
		},
		{
			MethodName: "NotifyPaymentLink",
			Handler:    _PagamentoService_NotifyPaymentLink_Handler,
		},
		{
			MethodName: "NotifyPaymentStatus",
			Handler:    _PagamentoService_NotifyPaymentStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pagamento/pagamento.proto",
}
