// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/lance/lance.proto

package lance

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LanceService_MakeBid_FullMethodName               = "/lance.LanceService/MakeBid"
	LanceService_GetHighestBid_FullMethodName         = "/lance.LanceService/GetHighestBid"
	LanceService_NotifyAuctionStarted_FullMethodName  = "/lance.LanceService/NotifyAuctionStarted"
	LanceService_NotifyAuctionFinished_FullMethodName = "/lance.LanceService/NotifyAuctionFinished"
	LanceService_NotifyBidValidated_FullMethodName    = "/lance.LanceService/NotifyBidValidated"
	LanceService_NotifyBidInvalidated_FullMethodName  = "/lance.LanceService/NotifyBidInvalidated"
)

// LanceServiceClient is the client API for LanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LanceServiceClient interface {
	MakeBid(ctx context.Context, in *MakeBidRequest, opts ...grpc.CallOption) (*MakeBidResponse, error)
	GetHighestBid(ctx context.Context, in *GetHighestBidRequest, opts ...grpc.CallOption) (*GetHighestBidResponse, error)
	NotifyAuctionStarted(ctx context.Context, in *AuctionStartedNotification, opts ...grpc.CallOption) (*Empty, error)
	NotifyAuctionFinished(ctx context.Context, in *AuctionFinishedNotification, opts ...grpc.CallOption) (*Empty, error)
	NotifyBidValidated(ctx context.Context, in *BidValidatedNotification, opts ...grpc.CallOption) (*Empty, error)
	NotifyBidInvalidated(ctx context.Context, in *BidInvalidatedNotification, opts ...grpc.CallOption) (*Empty, error)
}

type lanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLanceServiceClient(cc grpc.ClientConnInterface) LanceServiceClient {
	return &lanceServiceClient{cc}
}

func (c *lanceServiceClient) MakeBid(ctx context.Context, in *MakeBidRequest, opts ...grpc.CallOption) (*MakeBidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakeBidResponse)
	err := c.cc.Invoke(ctx, LanceService_MakeBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanceServiceClient) GetHighestBid(ctx context.Context, in *GetHighestBidRequest, opts ...grpc.CallOption) (*GetHighestBidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHighestBidResponse)
	err := c.cc.Invoke(ctx, LanceService_GetHighestBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanceServiceClient) NotifyAuctionStarted(ctx context.Context, in *AuctionStartedNotification, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LanceService_NotifyAuctionStarted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanceServiceClient) NotifyAuctionFinished(ctx context.Context, in *AuctionFinishedNotification, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LanceService_NotifyAuctionFinished_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanceServiceClient) NotifyBidValidated(ctx context.Context, in *BidValidatedNotification, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LanceService_NotifyBidValidated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanceServiceClient) NotifyBidInvalidated(ctx context.Context, in *BidInvalidatedNotification, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LanceService_NotifyBidInvalidated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LanceServiceServer is the server API for LanceService service.
// All implementations must embed UnimplementedLanceServiceServer
// for forward compatibility.
type LanceServiceServer interface {
	MakeBid(context.Context, *MakeBidRequest) (*MakeBidResponse, error)
	GetHighestBid(context.Context, *GetHighestBidRequest) (*GetHighestBidResponse, error)
	NotifyAuctionStarted(context.Context, *AuctionStartedNotification) (*Empty, error)
	NotifyAuctionFinished(context.Context, *AuctionFinishedNotification) (*Empty, error)
	NotifyBidValidated(context.Context, *BidValidatedNotification) (*Empty, error)
	NotifyBidInvalidated(context.Context, *BidInvalidatedNotification) (*Empty, error)
	mustEmbedUnimplementedLanceServiceServer()
}

// UnimplementedLanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLanceServiceServer struct{}

func (UnimplementedLanceServiceServer) MakeBid(context.Context, *MakeBidRequest) (*MakeBidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MakeBid not implemented")
}
func (UnimplementedLanceServiceServer) GetHighestBid(context.Context, *GetHighestBidRequest) (*GetHighestBidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHighestBid not implemented")
}
func (UnimplementedLanceServiceServer) NotifyAuctionStarted(context.Context, *AuctionStartedNotification) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyAuctionStarted not implemented")
}
func (UnimplementedLanceServiceServer) NotifyAuctionFinished(context.Context, *AuctionFinishedNotification) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyAuctionFinished not implemented")
}
func (UnimplementedLanceServiceServer) NotifyBidValidated(context.Context, *BidValidatedNotification) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyBidValidated not implemented")
}
func (UnimplementedLanceServiceServer) NotifyBidInvalidated(context.Context, *BidInvalidatedNotification) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyBidInvalidated not implemented")
}
func (UnimplementedLanceServiceServer) mustEmbedUnimplementedLanceServiceServer() {}
func (UnimplementedLanceServiceServer) testEmbeddedByValue()                      {}

// UnsafeLanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LanceServiceServer will
// result in compilation errors.
type UnsafeLanceServiceServer interface {
	mustEmbedUnimplementedLanceServiceServer()
}

func RegisterLanceServiceServer(s grpc.ServiceRegistrar, srv LanceServiceServer) {
	// If the following call panics, it indicates UnimplementedLanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LanceService_ServiceDesc, srv)
}

func _LanceService_MakeBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanceServiceServer).MakeBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanceService_MakeBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanceServiceServer).MakeBid(ctx, req.(*MakeBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanceService_GetHighestBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHighestBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanceServiceServer).GetHighestBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanceService_GetHighestBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanceServiceServer).GetHighestBid(ctx, req.(*GetHighestBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanceService_NotifyAuctionStarted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionStartedNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanceServiceServer).NotifyAuctionStarted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanceService_NotifyAuctionStarted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanceServiceServer).NotifyAuctionStarted(ctx, req.(*AuctionStartedNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanceService_NotifyAuctionFinished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionFinishedNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanceServiceServer).NotifyAuctionFinished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanceService_NotifyAuctionFinished_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanceServiceServer).NotifyAuctionFinished(ctx, req.(*AuctionFinishedNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanceService_NotifyBidValidated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidValidatedNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanceServiceServer).NotifyBidValidated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanceService_NotifyBidValidated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanceServiceServer).NotifyBidValidated(ctx, req.(*BidValidatedNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanceService_NotifyBidInvalidated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidInvalidatedNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanceServiceServer).NotifyBidInvalidated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanceService_NotifyBidInvalidated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanceServiceServer).NotifyBidInvalidated(ctx, req.(*BidInvalidatedNotification))
	}
	return interceptor(ctx, in, info, handler)
}

// LanceService_ServiceDesc is the grpc.ServiceDesc for LanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lance.LanceService",
	HandlerType: (*LanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeBid",
			Handler:    _LanceService_MakeBid_Handler,
		},
		{
			MethodName: "GetHighestBid",
			Handler:    _LanceService_GetHighestBid_Handler,
		},
		{
			MethodName: "NotifyAuctionStarted",
			Handler:    _LanceService_NotifyAuctionStarted_Handler,
		},
		{
			MethodName: "NotifyAuctionFinished",
			Handler:    _LanceService_NotifyAuctionFinished_Handler,
		},
		{
			MethodName: "NotifyBidValidated",
			Handler:    _LanceService_NotifyBidValidated_Handler,
		},
		{
			MethodName: "NotifyBidInvalidated",
			Handler:    _LanceService_NotifyBidInvalidated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lance/lance.proto",
}
