// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/lance/lance.proto

package lance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MakeBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LeilaoId      string                 `protobuf:"bytes,2,opt,name=leilao_id,json=leilaoId,proto3" json:"leilao_id,omitempty"`
	Valor         float64                `protobuf:"fixed64,3,opt,name=valor,proto3" json:"valor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeBidRequest) Reset() {
	*x = MakeBidRequest{}
	mi := &file_proto_lance_lance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeBidRequest) ProtoMessage() {}

func (x *MakeBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lance_lance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeBidRequest.ProtoReflect.Descriptor instead.
func (*MakeBidRequest) Descriptor() ([]byte, []int) {
	return file_proto_lance_lance_proto_rawDescGZIP(), []int{0}
}

func (x *MakeBidRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MakeBidRequest) GetLeilaoId() string {
	if x != nil {
		return x.LeilaoId
	}
	return ""
}

func (x *MakeBidRequest) GetValor() float64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

type MakeBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeBidResponse) Reset() {
	*x = MakeBidResponse{}
	mi := &file_proto_lance_lance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeBidResponse) ProtoMessage() {}

func (x *MakeBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lance_lance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeBidResponse.ProtoReflect.Descriptor instead.
func (*MakeBidResponse) Descriptor() ([]byte, []int) {
	return file_proto_lance_lance_proto_rawDescGZIP(), []int{1}
}

func (x *MakeBidResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MakeBidResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetHighestBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeilaoId      string                 `protobuf:"bytes,1,opt,name=leilao_id,json=leilaoId,proto3" json:"leilao_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHighestBidRequest) Reset() {
	*x = GetHighestBidRequest{}
	mi := &file_proto_lance_lance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHighestBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHighestBidRequest) ProtoMessage() {}

func (x *GetHighestBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lance_lance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHighestBidRequest.ProtoReflect.Descriptor instead.
func (*GetHighestBidRequest) Descriptor() ([]byte, []int) {
	return file_proto_lance_lance_proto_rawDescGZIP(), []int{2}
}

func (x *GetHighestBidRequest) GetLeilaoId() string {
	if x != nil {
		return x.LeilaoId
	}
	return ""
}

type GetHighestBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HighestBid    float64                `protobuf:"fixed64,1,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	LeilaoId      string                 `protobuf:"bytes,2,opt,name=leilao_id,json=leilaoId,proto3" json:"leilao_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHighestBidResponse) Reset() {
	*x = GetHighestBidResponse{}
	mi := &file_proto_lance_lance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHighestBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHighestBidResponse) ProtoMessage() {}

func (x *GetHighestBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lance_lance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHighestBidResponse.ProtoReflect.Descriptor instead.
func (*GetHighestBidResponse) Descriptor() ([]byte, []int) {
	return file_proto_lance_lance_proto_rawDescGZIP(), []int{3}
}

func (x *GetHighestBidResponse) GetHighestBid() float64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *GetHighestBidResponse) GetLeilaoId() string {
	if x != nil {
		return x.LeilaoId
	}
	return ""
}

type AuctionStartedNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeilaoId      string                 `protobuf:"bytes,1,opt,name=leilao_id,json=leilaoId,proto3" json:"leilao_id,omitempty"`
	Duracao       int64                  `protobuf:"varint,2,opt,name=duracao,proto3" json:"duracao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionStartedNotification) Reset() {
	*x = AuctionStartedNotification{}
	mi := &file_proto_lance_lance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionStartedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionStartedNotification) ProtoMessage() {}

func (x *AuctionStartedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lance_lance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionStartedNotification.ProtoReflect.Descriptor instead.
func (*AuctionStartedNotification) Descriptor() ([]byte, []int) {
	return file_proto_lance_lance_proto_rawDescGZIP(), []int{4}
}

func (x *AuctionStartedNotification) GetLeilaoId() string {
	if x != nil {
		return x.LeilaoId
	}
	return ""
}

func (x *AuctionStartedNotification) GetDuracao() int64 {
	if x != nil {
		return x.Duracao
	}
	return 0
}

type AuctionFinishedNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeilaoId      string                 `protobuf:"bytes,1,opt,name=leilao_id,json=leilaoId,proto3" json:"leilao_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionFinishedNotification) Reset() {
	*x = AuctionFinishedNotification{}
	mi := &file_proto_lance_lance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionFinishedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionFinishedNotification) ProtoMessage() {}

func (x *AuctionFinishedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lance_lance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionFinishedNotification.ProtoReflect.Descriptor instead.
func (*AuctionFinishedNotification) Descriptor() ([]byte, []int) {
	return file_proto_lance_lance_proto_rawDescGZIP(), []int{5}
}

func (x *AuctionFinishedNotification) GetLeilaoId() string {
	if x != nil {
		return x.LeilaoId
	}
	return ""
}

type GetAuctionWinnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeilaoId      string                 `protobuf:"bytes,1,opt,name=leilao_id,json=leilaoId,proto3" json:"leilao_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionWinnerRequest) Reset() {
	*x = GetAuctionWinnerRequest{}
	mi := &file_proto_lance_lance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionWinnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionWinnerRequest) ProtoMessage() {}

func (x *GetAuctionWinnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lance_lance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionWinnerRequest.ProtoReflect.Descriptor instead.
func (*GetAuctionWinnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lance_lance_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuctionWinnerRequest) GetLeilaoId() string {
	if x != nil {
		return x.LeilaoId
	}
	return ""
}

type GetAuctionWinnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Valor         float64                `protobuf:"fixed64,2,opt,name=valor,proto3" json:"valor,omitempty"`
	HasWinner     bool                   `protobuf:"varint,3,opt,name=has_winner,json=hasWinner,proto3" json:"has_winner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionWinnerResponse) Reset() {
	*x = GetAuctionWinnerResponse{}
	mi := &file_proto_lance_lance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionWinnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionWinnerResponse) ProtoMessage() {}

func (x *GetAuctionWinnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lance_lance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionWinnerResponse.ProtoReflect.Descriptor instead.
func (*GetAuctionWinnerResponse) Descriptor() ([]byte, []int) {
	return file_proto_lance_lance_proto_rawDescGZIP(), []int{7}
}

func (x *GetAuctionWinnerResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAuctionWinnerResponse) GetValor() float64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *GetAuctionWinnerResponse) GetHasWinner() bool {
	if x != nil {
		return x.HasWinner
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_lance_lance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lance_lance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_lance_lance_proto_rawDescGZIP(), []int{8}
}

var File_proto_lance_lance_proto protoreflect.FileDescriptor

const file_proto_lance_lance_proto_rawDesc = "" +
	"\n" +
	"\x17proto/lance/lance.proto\x12\x05lance\"\\\n" +
	"\x0eMakeBidRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tleilao_id\x18\x02 \x01(\tR\bleilaoId\x12\x14\n" +
	"\x05valor\x18\x03 \x01(\x01R\x05valor\"A\n" +
	"\x0fMakeBidResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"3\n" +
	"\x14GetHighestBidRequest\x12\x1b\n" +
	"\tleilao_id\x18\x01 \x01(\tR\bleilaoId\"U\n" +
	"\x15GetHighestBidResponse\x12\x1f\n" +
	"\vhighest_bid\x18\x01 \x01(\x01R\n" +
	"highestBid\x12\x1b\n" +
	"\tleilao_id\x18\x02 \x01(\tR\bleilaoId\"S\n" +
	"\x1aAuctionStartedNotification\x12\x1b\n" +
	"\tleilao_id\x18\x01 \x01(\tR\bleilaoId\x12\x18\n" +
	"\aduracao\x18\x02 \x01(\x03R\aduracao\":\n" +
	"\x1bAuctionFinishedNotification\x12\x1b\n" +
	"\tleilao_id\x18\x01 \x01(\tR\bleilaoId\"6\n" +
	"\x17GetAuctionWinnerRequest\x12\x1b\n" +
	"\tleilao_id\x18\x01 \x01(\tR\bleilaoId\"h\n" +
	"\x18GetAuctionWinnerResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05valor\x18\x02 \x01(\x01R\x05valor\x12\x1d\n" +
	"\n" +
	"has_winner\x18\x03 \x01(\bR\thasWinner\"\a\n" +
	"\x05Empty2\xfd\x02\n" +
	"\fLanceService\x128\n" +
	"\aMakeBid\x12\x15.lance.MakeBidRequest\x1a\x16.lance.MakeBidResponse\x12J\n" +
	"\rGetHighestBid\x12\x1b.lance.GetHighestBidRequest\x1a\x1c.lance.GetHighestBidResponse\x12G\n" +
	"\x14NotifyAuctionStarted\x12!.lance.AuctionStartedNotification\x1a\f.lance.Empty\x12I\n" +
	"\x15NotifyAuctionFinished\x12\".lance.AuctionFinishedNotification\x1a\f.lance.Empty\x12S\n" +
	"\x10GetAuctionWinner\x12\x1e.lance.GetAuctionWinnerRequest\x1a\x1f.lance.GetAuctionWinnerResponseB\x1cZ\x1aauction-system/proto/lanceb\x06proto3"

var (
	file_proto_lance_lance_proto_rawDescOnce sync.Once
	file_proto_lance_lance_proto_rawDescData []byte
)

func file_proto_lance_lance_proto_rawDescGZIP() []byte {
	file_proto_lance_lance_proto_rawDescOnce.Do(func() {
		file_proto_lance_lance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lance_lance_proto_rawDesc), len(file_proto_lance_lance_proto_rawDesc)))
	})
	return file_proto_lance_lance_proto_rawDescData
}

var file_proto_lance_lance_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_lance_lance_proto_goTypes = []any{
	(*MakeBidRequest)(nil),              // 0: lance.MakeBidRequest
	(*MakeBidResponse)(nil),             // 1: lance.MakeBidResponse
	(*GetHighestBidRequest)(nil),        // 2: lance.GetHighestBidRequest
	(*GetHighestBidResponse)(nil),       // 3: lance.GetHighestBidResponse
	(*AuctionStartedNotification)(nil),  // 4: lance.AuctionStartedNotification
	(*AuctionFinishedNotification)(nil), // 5: lance.AuctionFinishedNotification
	(*GetAuctionWinnerRequest)(nil),     // 6: lance.GetAuctionWinnerRequest
	(*GetAuctionWinnerResponse)(nil),    // 7: lance.GetAuctionWinnerResponse
	(*Empty)(nil),                       // 8: lance.Empty
}
var file_proto_lance_lance_proto_depIdxs = []int32{
	0, // 0: lance.LanceService.MakeBid:input_type -> lance.MakeBidRequest
	2, // 1: lance.LanceService.GetHighestBid:input_type -> lance.GetHighestBidRequest
	4, // 2: lance.LanceService.NotifyAuctionStarted:input_type -> lance.AuctionStartedNotification
	5, // 3: lance.LanceService.NotifyAuctionFinished:input_type -> lance.AuctionFinishedNotification
	6, // 4: lance.LanceService.GetAuctionWinner:input_type -> lance.GetAuctionWinnerRequest
	1, // 5: lance.LanceService.MakeBid:output_type -> lance.MakeBidResponse
	3, // 6: lance.LanceService.GetHighestBid:output_type -> lance.GetHighestBidResponse
	8, // 7: lance.LanceService.NotifyAuctionStarted:output_type -> lance.Empty
	8, // 8: lance.LanceService.NotifyAuctionFinished:output_type -> lance.Empty
	7, // 9: lance.LanceService.GetAuctionWinner:output_type -> lance.GetAuctionWinnerResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_lance_lance_proto_init() }
func file_proto_lance_lance_proto_init() {
	if File_proto_lance_lance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lance_lance_proto_rawDesc), len(file_proto_lance_lance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lance_lance_proto_goTypes,
		DependencyIndexes: file_proto_lance_lance_proto_depIdxs,
		MessageInfos:      file_proto_lance_lance_proto_msgTypes,
	}.Build()
	File_proto_lance_lance_proto = out.File
	file_proto_lance_lance_proto_goTypes = nil
	file_proto_lance_lance_proto_depIdxs = nil
}
