// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/gateway/gateway.proto

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_NotifyAuctionFinished_FullMethodName = "/gateway.GatewayService/NotifyAuctionFinished"
	GatewayService_NotifyPaymentLink_FullMethodName     = "/gateway.GatewayService/NotifyPaymentLink"
	GatewayService_NotifyPaymentStatus_FullMethodName   = "/gateway.GatewayService/NotifyPaymentStatus"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	NotifyAuctionFinished(ctx context.Context, in *AuctionFinishedNotification, opts ...grpc.CallOption) (*Empty, error)
	NotifyPaymentLink(ctx context.Context, in *PaymentLinkNotification, opts ...grpc.CallOption) (*Empty, error)
	NotifyPaymentStatus(ctx context.Context, in *PaymentStatusNotification, opts ...grpc.CallOption) (*Empty, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) NotifyAuctionFinished(ctx context.Context, in *AuctionFinishedNotification, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GatewayService_NotifyAuctionFinished_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) NotifyPaymentLink(ctx context.Context, in *PaymentLinkNotification, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GatewayService_NotifyPaymentLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) NotifyPaymentStatus(ctx context.Context, in *PaymentStatusNotification, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GatewayService_NotifyPaymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	NotifyAuctionFinished(context.Context, *AuctionFinishedNotification) (*Empty, error)
	NotifyPaymentLink(context.Context, *PaymentLinkNotification) (*Empty, error)
	NotifyPaymentStatus(context.Context, *PaymentStatusNotification) (*Empty, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) NotifyAuctionFinished(context.Context, *AuctionFinishedNotification) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyAuctionFinished not implemented")
}
func (UnimplementedGatewayServiceServer) NotifyPaymentLink(context.Context, *PaymentLinkNotification) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyPaymentLink not implemented")
}
func (UnimplementedGatewayServiceServer) NotifyPaymentStatus(context.Context, *PaymentStatusNotification) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyPaymentStatus not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_NotifyAuctionFinished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionFinishedNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).NotifyAuctionFinished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_NotifyAuctionFinished_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).NotifyAuctionFinished(ctx, req.(*AuctionFinishedNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_NotifyPaymentLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentLinkNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).NotifyPaymentLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_NotifyPaymentLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).NotifyPaymentLink(ctx, req.(*PaymentLinkNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_NotifyPaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentStatusNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).NotifyPaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_NotifyPaymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).NotifyPaymentStatus(ctx, req.(*PaymentStatusNotification))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyAuctionFinished",
			Handler:    _GatewayService_NotifyAuctionFinished_Handler,
		},
		{
			MethodName: "NotifyPaymentLink",
			Handler:    _GatewayService_NotifyPaymentLink_Handler,
		},
		{
			MethodName: "NotifyPaymentStatus",
			Handler:    _GatewayService_NotifyPaymentStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gateway/gateway.proto",
}
