// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/gateway/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentLinkNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PaymentLink   string                 `protobuf:"bytes,2,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AuctionId     string                 `protobuf:"bytes,4,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentLinkNotification) Reset() {
	*x = PaymentLinkNotification{}
	mi := &file_proto_gateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentLinkNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentLinkNotification) ProtoMessage() {}

func (x *PaymentLinkNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentLinkNotification.ProtoReflect.Descriptor instead.
func (*PaymentLinkNotification) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentLinkNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentLinkNotification) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

func (x *PaymentLinkNotification) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentLinkNotification) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

type PaymentStatusNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AuctionId     string                 `protobuf:"bytes,3,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	WinnerId      string                 `protobuf:"bytes,4,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentStatusNotification) Reset() {
	*x = PaymentStatusNotification{}
	mi := &file_proto_gateway_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentStatusNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentStatusNotification) ProtoMessage() {}

func (x *PaymentStatusNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentStatusNotification.ProtoReflect.Descriptor instead.
func (*PaymentStatusNotification) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentStatusNotification) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentStatusNotification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentStatusNotification) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *PaymentStatusNotification) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

func (x *PaymentStatusNotification) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AuctionFinishedNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeilaoId      string                 `protobuf:"bytes,1,opt,name=leilao_id,json=leilaoId,proto3" json:"leilao_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionFinishedNotification) Reset() {
	*x = AuctionFinishedNotification{}
	mi := &file_proto_gateway_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionFinishedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionFinishedNotification) ProtoMessage() {}

func (x *AuctionFinishedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionFinishedNotification.ProtoReflect.Descriptor instead.
func (*AuctionFinishedNotification) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *AuctionFinishedNotification) GetLeilaoId() string {
	if x != nil {
		return x.LeilaoId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_gateway_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

var File_proto_gateway_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/gateway/gateway.proto\x12\agateway\"\x9b\x01\n" +
	"\x17PaymentLinkNotification\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fpayment_link\x18\x02 \x01(\tR\vpaymentLink\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x04 \x01(\tR\tauctionId\"\xae\x01\n" +
	"\x19PaymentStatusNotification\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x03 \x01(\tR\tauctionId\x12\x1b\n" +
	"\twinner_id\x18\x04 \x01(\tR\bwinnerId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\":\n" +
	"\x1bAuctionFinishedNotification\x12\x1b\n" +
	"\tleilao_id\x18\x01 \x01(\tR\bleilaoId\"\a\n" +
	"\x05Empty2\xf1\x01\n" +
	"\x0eGatewayService\x12M\n" +
	"\x15NotifyAuctionFinished\x12$.gateway.AuctionFinishedNotification\x1a\x0e.gateway.Empty\x12E\n" +
	"\x11NotifyPaymentLink\x12 .gateway.PaymentLinkNotification\x1a\x0e.gateway.Empty\x12I\n" +
	"\x13NotifyPaymentStatus\x12\".gateway.PaymentStatusNotification\x1a\x0e.gateway.EmptyB\x1eZ\x1cauction-system/proto/gatewayb\x06proto3"

var (
	file_proto_gateway_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_gateway_proto_rawDescData []byte
)

func file_proto_gateway_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_gateway_proto_rawDesc), len(file_proto_gateway_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_gateway_proto_rawDescData
}

var file_proto_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_gateway_gateway_proto_goTypes = []any{
	(*PaymentLinkNotification)(nil),     // 0: gateway.PaymentLinkNotification
	(*PaymentStatusNotification)(nil),   // 1: gateway.PaymentStatusNotification
	(*AuctionFinishedNotification)(nil), // 2: gateway.AuctionFinishedNotification
	(*Empty)(nil),                       // 3: gateway.Empty
}
var file_proto_gateway_gateway_proto_depIdxs = []int32{
	2, // 0: gateway.GatewayService.NotifyAuctionFinished:input_type -> gateway.AuctionFinishedNotification
	0, // 1: gateway.GatewayService.NotifyPaymentLink:input_type -> gateway.PaymentLinkNotification
	1, // 2: gateway.GatewayService.NotifyPaymentStatus:input_type -> gateway.PaymentStatusNotification
	3, // 3: gateway.GatewayService.NotifyAuctionFinished:output_type -> gateway.Empty
	3, // 4: gateway.GatewayService.NotifyPaymentLink:output_type -> gateway.Empty
	3, // 5: gateway.GatewayService.NotifyPaymentStatus:output_type -> gateway.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gateway_gateway_proto_init() }
func file_proto_gateway_gateway_proto_init() {
	if File_proto_gateway_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_gateway_proto_rawDesc), len(file_proto_gateway_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_gateway_proto = out.File
	file_proto_gateway_gateway_proto_goTypes = nil
	file_proto_gateway_gateway_proto_depIdxs = nil
}
