// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/leilao/leilao.proto

package leilao

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeilaoService_CreateAuction_FullMethodName   = "/leilao.LeilaoService/CreateAuction"
	LeilaoService_ConsultAuctions_FullMethodName = "/leilao.LeilaoService/ConsultAuctions"
)

// LeilaoServiceClient is the client API for LeilaoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeilaoServiceClient interface {
	CreateAuction(ctx context.Context, in *CreateAuctionRequest, opts ...grpc.CallOption) (*CreateAuctionResponse, error)
	ConsultAuctions(ctx context.Context, in *ConsultAuctionsRequest, opts ...grpc.CallOption) (*ConsultAuctionsResponse, error)
}

type leilaoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeilaoServiceClient(cc grpc.ClientConnInterface) LeilaoServiceClient {
	return &leilaoServiceClient{cc}
}

func (c *leilaoServiceClient) CreateAuction(ctx context.Context, in *CreateAuctionRequest, opts ...grpc.CallOption) (*CreateAuctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAuctionResponse)
	err := c.cc.Invoke(ctx, LeilaoService_CreateAuction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leilaoServiceClient) ConsultAuctions(ctx context.Context, in *ConsultAuctionsRequest, opts ...grpc.CallOption) (*ConsultAuctionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultAuctionsResponse)
	err := c.cc.Invoke(ctx, LeilaoService_ConsultAuctions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeilaoServiceServer is the server API for LeilaoService service.
// All implementations must embed UnimplementedLeilaoServiceServer
// for forward compatibility.
type LeilaoServiceServer interface {
	CreateAuction(context.Context, *CreateAuctionRequest) (*CreateAuctionResponse, error)
	ConsultAuctions(context.Context, *ConsultAuctionsRequest) (*ConsultAuctionsResponse, error)
	mustEmbedUnimplementedLeilaoServiceServer()
}

// UnimplementedLeilaoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeilaoServiceServer struct{}

func (UnimplementedLeilaoServiceServer) CreateAuction(context.Context, *CreateAuctionRequest) (*CreateAuctionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAuction not implemented")
}
func (UnimplementedLeilaoServiceServer) ConsultAuctions(context.Context, *ConsultAuctionsRequest) (*ConsultAuctionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultAuctions not implemented")
}
func (UnimplementedLeilaoServiceServer) mustEmbedUnimplementedLeilaoServiceServer() {}
func (UnimplementedLeilaoServiceServer) testEmbeddedByValue()                       {}

// UnsafeLeilaoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeilaoServiceServer will
// result in compilation errors.
type UnsafeLeilaoServiceServer interface {
	mustEmbedUnimplementedLeilaoServiceServer()
}

func RegisterLeilaoServiceServer(s grpc.ServiceRegistrar, srv LeilaoServiceServer) {
	// If the following call panics, it indicates UnimplementedLeilaoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeilaoService_ServiceDesc, srv)
}

func _LeilaoService_CreateAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeilaoServiceServer).CreateAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeilaoService_CreateAuction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeilaoServiceServer).CreateAuction(ctx, req.(*CreateAuctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeilaoService_ConsultAuctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultAuctionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeilaoServiceServer).ConsultAuctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeilaoService_ConsultAuctions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeilaoServiceServer).ConsultAuctions(ctx, req.(*ConsultAuctionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeilaoService_ServiceDesc is the grpc.ServiceDesc for LeilaoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeilaoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leilao.LeilaoService",
	HandlerType: (*LeilaoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAuction",
			Handler:    _LeilaoService_CreateAuction_Handler,
		},
		{
			MethodName: "ConsultAuctions",
			Handler:    _LeilaoService_ConsultAuctions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/leilao/leilao.proto",
}
