// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/leilao/leilao.proto

package leilao

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Start         string                 `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuctionRequest) Reset() {
	*x = CreateAuctionRequest{}
	mi := &file_proto_leilao_leilao_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuctionRequest) ProtoMessage() {}

func (x *CreateAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leilao_leilao_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuctionRequest.ProtoReflect.Descriptor instead.
func (*CreateAuctionRequest) Descriptor() ([]byte, []int) {
	return file_proto_leilao_leilao_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAuctionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAuctionRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *CreateAuctionRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

type CreateAuctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeilaoId      string                 `protobuf:"bytes,1,opt,name=leilao_id,json=leilaoId,proto3" json:"leilao_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuctionResponse) Reset() {
	*x = CreateAuctionResponse{}
	mi := &file_proto_leilao_leilao_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuctionResponse) ProtoMessage() {}

func (x *CreateAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leilao_leilao_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuctionResponse.ProtoReflect.Descriptor instead.
func (*CreateAuctionResponse) Descriptor() ([]byte, []int) {
	return file_proto_leilao_leilao_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAuctionResponse) GetLeilaoId() string {
	if x != nil {
		return x.LeilaoId
	}
	return ""
}

func (x *CreateAuctionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateAuctionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConsultAuctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultAuctionsRequest) Reset() {
	*x = ConsultAuctionsRequest{}
	mi := &file_proto_leilao_leilao_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultAuctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultAuctionsRequest) ProtoMessage() {}

func (x *ConsultAuctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leilao_leilao_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultAuctionsRequest.ProtoReflect.Descriptor instead.
func (*ConsultAuctionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_leilao_leilao_proto_rawDescGZIP(), []int{2}
}

type ConsultAuctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auctions      []*Auction             `protobuf:"bytes,1,rep,name=auctions,proto3" json:"auctions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultAuctionsResponse) Reset() {
	*x = ConsultAuctionsResponse{}
	mi := &file_proto_leilao_leilao_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultAuctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultAuctionsResponse) ProtoMessage() {}

func (x *ConsultAuctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leilao_leilao_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultAuctionsResponse.ProtoReflect.Descriptor instead.
func (*ConsultAuctionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_leilao_leilao_proto_rawDescGZIP(), []int{3}
}

func (x *ConsultAuctionsResponse) GetAuctions() []*Auction {
	if x != nil {
		return x.Auctions
	}
	return nil
}

type Auction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Start         string                 `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auction) Reset() {
	*x = Auction{}
	mi := &file_proto_leilao_leilao_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auction) ProtoMessage() {}

func (x *Auction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leilao_leilao_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auction.ProtoReflect.Descriptor instead.
func (*Auction) Descriptor() ([]byte, []int) {
	return file_proto_leilao_leilao_proto_rawDescGZIP(), []int{4}
}

func (x *Auction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Auction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Auction) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Auction) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *Auction) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_leilao_leilao_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leilao_leilao_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_leilao_leilao_proto_rawDescGZIP(), []int{5}
}

var File_proto_leilao_leilao_proto protoreflect.FileDescriptor

const file_proto_leilao_leilao_proto_rawDesc = "" +
	"\n" +
	"\x19proto/leilao/leilao.proto\x12\x06leilao\"`\n" +
	"\x14CreateAuctionRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\x12\x14\n" +
	"\x05start\x18\x03 \x01(\tR\x05start\"d\n" +
	"\x15CreateAuctionResponse\x12\x1b\n" +
	"\tleilao_id\x18\x01 \x01(\tR\bleilaoId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x18\n" +
	"\x16ConsultAuctionsRequest\"F\n" +
	"\x17ConsultAuctionsResponse\x12+\n" +
	"\bauctions\x18\x01 \x03(\v2\x0f.leilao.AuctionR\bauctions\"{\n" +
	"\aAuction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05start\x18\x03 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\tR\x03end\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\"\a\n" +
	"\x05Empty2\xb1\x01\n" +
	"\rLeilaoService\x12L\n" +
	"\rCreateAuction\x12\x1c.leilao.CreateAuctionRequest\x1a\x1d.leilao.CreateAuctionResponse\x12R\n" +
	"\x0fConsultAuctions\x12\x1e.leilao.ConsultAuctionsRequest\x1a\x1f.leilao.ConsultAuctionsResponseB\x1dZ\x1bauction-system/proto/leilaob\x06proto3"

var (
	file_proto_leilao_leilao_proto_rawDescOnce sync.Once
	file_proto_leilao_leilao_proto_rawDescData []byte
)

func file_proto_leilao_leilao_proto_rawDescGZIP() []byte {
	file_proto_leilao_leilao_proto_rawDescOnce.Do(func() {
		file_proto_leilao_leilao_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_leilao_leilao_proto_rawDesc), len(file_proto_leilao_leilao_proto_rawDesc)))
	})
	return file_proto_leilao_leilao_proto_rawDescData
}

var file_proto_leilao_leilao_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_leilao_leilao_proto_goTypes = []any{
	(*CreateAuctionRequest)(nil),    // 0: leilao.CreateAuctionRequest
	(*CreateAuctionResponse)(nil),   // 1: leilao.CreateAuctionResponse
	(*ConsultAuctionsRequest)(nil),  // 2: leilao.ConsultAuctionsRequest
	(*ConsultAuctionsResponse)(nil), // 3: leilao.ConsultAuctionsResponse
	(*Auction)(nil),                 // 4: leilao.Auction
	(*Empty)(nil),                   // 5: leilao.Empty
}
var file_proto_leilao_leilao_proto_depIdxs = []int32{
	4, // 0: leilao.ConsultAuctionsResponse.auctions:type_name -> leilao.Auction
	0, // 1: leilao.LeilaoService.CreateAuction:input_type -> leilao.CreateAuctionRequest
	2, // 2: leilao.LeilaoService.ConsultAuctions:input_type -> leilao.ConsultAuctionsRequest
	1, // 3: leilao.LeilaoService.CreateAuction:output_type -> leilao.CreateAuctionResponse
	3, // 4: leilao.LeilaoService.ConsultAuctions:output_type -> leilao.ConsultAuctionsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_leilao_leilao_proto_init() }
func file_proto_leilao_leilao_proto_init() {
	if File_proto_leilao_leilao_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_leilao_leilao_proto_rawDesc), len(file_proto_leilao_leilao_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_leilao_leilao_proto_goTypes,
		DependencyIndexes: file_proto_leilao_leilao_proto_depIdxs,
		MessageInfos:      file_proto_leilao_leilao_proto_msgTypes,
	}.Build()
	File_proto_leilao_leilao_proto = out.File
	file_proto_leilao_leilao_proto_goTypes = nil
	file_proto_leilao_leilao_proto_depIdxs = nil
}
